FROM python:alpine

RUN apk add --update npm openssh git
RUN pip3 install redis aiqDocTests

WORKDIR tests-back

COPY tests/.env.test .env
COPY .aiqdoctests.config .aiqdoctests.config

COPY tests/ tests/
